name: Docker Build and Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t asupan/skinet-test:latest .

    - name: Push Docker image
      run: docker push asupan/skinet-test:latest

  update-compose:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Update Docker Compose on Remote Server
      uses: peter-evans/ssh-run@v2
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: root
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
